language: php

php:
    - '5.6'
    - '7.0'
    - '7.1'

install:
    - 'composer install --prefer-dist --no-suggest'

script:
    - 'cd test && ../vendor/bin/phpunit -c phpunit.xml'

cache:
  directories:
    - '$HOME/.composer/cache'
