dist: trusty
sudo: false

language: php

php:
    - '5.6'
    - '7.0'
    - '7.1'

install:
    - 'composer install --prefer-dist --no-suggest'

before_script:
    - |
        # APCu is only available for PHP 7.x
        if [[ $TRAVIS_PHP_VERSION = 7.* ]]; then
            echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        fi

script:
    - 'cd test && ../vendor/bin/phpunit -c phpunit.xml --debug'

cache:
  directories:
    - '$HOME/.composer/cache'
