dist: trusty
sudo: false

language: php

php:
    - '5.6'
    - '7.0'
    - '7.1'

install:
    - 'composer install --prefer-dist --no-suggest'

before_script:
    - 'echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini'
    - 'echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini'

script:
    - 'cd test && ../vendor/bin/phpunit -c phpunit.xml --debug'

cache:
  directories:
    - '$HOME/.composer/cache'
